spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/hello-springboot-db?ssl=false
    username: andromediano
    password: q1w2e3r4
    hikari:
      connection-test-query: SELECT 1
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
  ## JPA
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
