/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  id("application-conventions")
  id("org.springframework.boot")
  id("io.spring.dependency-management")
  id("io.freefair.lombok")
}

dependencies {
  //implementation("org.apache.commons:commons-text")
  implementation(project(":judymall-domain"))

  implementation("org.springframework.boot:spring-boot-starter-web")
}

application {
  // Define the main class for the application.
  mainClass.set("io.opentest.app.App")
}
