/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  // Apply the java Plugin to add support for Java.
  java
}

val projectGroup: String by project
val projectVersion: String by project

group = projectGroup
version = projectVersion
java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

dependencies {
  constraints {
    // Define dependency versions as constraints
    //implementation("org.apache.commons:commons-text:1.9")
  }

  // Use JUnit Jupiter for testing.
  testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")
}

tasks.test {
  // Use JUnit Platform for unit tests.
  useJUnitPlatform()
}
