#
# FrontApp
#
server:
  port: 8080
  # https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.developing-web-applications.spring-mvc.error-handling
  error:
    whitelabel:
      enabled: false

spring:
  config:
    import:
      - optional:classpath:/application-core.yml
      - optional:classpath:/application-domain.yml

myapp:
  app-code: front
  ajp-port: 8009

---

spring:
  config:
    activate:
      on-profile: development
